[package]
name = "pareto_front"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = {version="0.3.5", features=["html_reports"]}
rand = "0.8.4"

[[bench]]
name = "several_push"
harness = false
